import { useCallback, useEffect, useState } from 'react'
import { AdminShell } from '../components/AdminShell'
import api from '../lib/api'
import type { BookingRecord, Paginated } from '../types'

export default function BookingsPage() {
  const [bookings, setBookings] = useState<BookingRecord[]>([]); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const loadBookings = useCallback(() => { setLoading(true); api.get<Paginated<BookingRecord>>(`/bookings?per_page=50${status ? `&status=${status}` : ''}`).then(result => setBookings(result.data.data)).catch(e => setError(e instanceof Error ? e.message : 'Unable to load bookings')).finally(() => setLoading(false)) }, [status])
  useEffect(() => { const timer = window.setTimeout(loadBookings, 0); return () => window.clearTimeout(timer) }, [loadBookings])
  const updateStatus = async (booking: BookingRecord, nextStatus: string) => { try { await api.patch(`/bookings/${booking.id}`, { status: nextStatus }); loadBookings() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update booking') } }
  return <AdminShell title="Booking management"><div className="mt-8 border border-black/10 bg-white p-4 md:p-6"><div className="flex justify-between"><p className="text-sm text-[#777]">Review and update rental requests.</p><select className="border border-black/10 bg-[#f8f7f5] px-4 py-3 text-sm" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{['pending', 'confirmed', 'active', 'completed', 'cancelled', 'rejected'].map(value => <option key={value}>{value}</option>)}</select></div>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-black/10 text-[10px] uppercase tracking-widest text-[#888]"><tr><th className="pb-3">Reference</th><th className="pb-3">Customer</th><th className="pb-3">Vehicle</th><th className="pb-3">Dates</th><th className="pb-3">Total</th><th className="pb-3">Status</th></tr></thead><tbody>{loading ? <tr><td className="py-8 text-[#888]" colSpan={6}>Loading bookings...</td></tr> : bookings.map(booking => <tr className="border-b border-black/[.06]" key={booking.id}><td className="py-4 font-semibold text-[#ff641f]">{booking.reference}</td><td className="py-4">{booking.customer?.name ?? '—'}</td><td className="py-4 text-[#777]">{booking.vehicle ? `${booking.vehicle.brand} ${booking.vehicle.model}` : '—'}</td><td className="py-4 text-xs text-[#777]">{new Date(booking.pickup_at).toLocaleDateString()} → {new Date(booking.return_at).toLocaleDateString()}</td><td className="py-4">₱{Number(booking.total_amount).toLocaleString()}</td><td className="py-4"><select className="border border-black/10 bg-[#f8f7f5] px-2 py-1 text-xs capitalize" value={booking.status} onChange={e => updateStatus(booking, e.target.value)}>{['pending', 'confirmed', 'active', 'completed', 'cancelled', 'rejected'].map(value => <option key={value}>{value}</option>)}</select></td></tr>)}</tbody></table></div></div></AdminShell>
}
