import { useEffect, useMemo, useState, type FormEvent } from "react";
import { AdminShell } from "../components/AdminShell";
import { DateTimePicker } from "../components/DateTimePicker";
import { RowActions, useToast } from "../components/Ui";
import api from "../lib/api";
import type { FundRecord, FundTransactionRecord } from "../types";

type Response = { funds: FundRecord[]; transactions: FundTransactionRecord[]; total_balance: number; total_inflows: number; total_outflows: number };
const money = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" });
const dateNow = () => new Date().toISOString().slice(0, 16);
const dateLabel = (value: string) => new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });

export default function FundsPage() {
  const { showToast } = useToast();
  const [data, setData] = useState<Response | null>(null);
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState("date_latest");
  const [fundId, setFundId] = useState("");
  const [type, setType] = useState("");
  const [modal, setModal] = useState<"fund" | "transaction" | null>(null);
  const [editingFund, setEditingFund] = useState<FundRecord | null>(null);
  const [editingTransaction, setEditingTransaction] = useState<FundTransactionRecord | null>(null);
  const [selectedTransaction, setSelectedTransaction] = useState<FundTransactionRecord | null>(null);
  const [name, setName] = useState(""); const [fundType, setFundType] = useState("cash"); const [opening, setOpening] = useState("0"); const [fundNotes, setFundNotes] = useState("");
  const [accountName, setAccountName] = useState(""); const [accountNumber, setAccountNumber] = useState(""); const [qrCode, setQrCode] = useState<File | null>(null);
  const [transactionType, setTransactionType] = useState<"inflow" | "outflow">("inflow"); const [transactionFund, setTransactionFund] = useState(""); const [transactedAt, setTransactedAt] = useState(dateNow()); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [transactionNotes, setTransactionNotes] = useState(""); const [saving, setSaving] = useState(false);

  const load = () => { const params = new URLSearchParams({ sort }); if (search.trim()) params.set("search", search.trim()); if (fundId) params.set("fund_id", fundId); if (type) params.set("type", type); api.get<Response>(`/funds?${params}`).then(result => setData(result.data)).catch(error => showToast(error instanceof Error ? error.message : "Unable to load funds", "error")); };
  useEffect(() => { const timer = window.setTimeout(load, 250); return () => window.clearTimeout(timer); }, [search, sort, fundId, type]);
  const resetFund = () => { setEditingFund(null); setName(""); setFundType("cash"); setOpening("0"); setFundNotes(""); setAccountName(""); setAccountNumber(""); setQrCode(null); };
  const resetTransaction = () => { setEditingTransaction(null); setTransactionType("inflow"); setTransactionFund(data?.funds[0] ? String(data.funds[0].id) : ""); setTransactedAt(dateNow()); setAmount(""); setDescription(""); setTransactionNotes(""); };
  const submitFund = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const payload = new FormData(); payload.append("name", name); payload.append("type", fundType); payload.append("opening_balance", opening); payload.append("notes", fundNotes); payload.append("account_name", accountName); payload.append("account_number", accountNumber); if (qrCode) payload.append("qr_code", qrCode); if (editingFund) { payload.append("_method", "PATCH"); await api.post(`/funds/${editingFund.id}`, payload); } else await api.post("/funds", payload); showToast(editingFund ? "Fund updated." : "Fund created.", "success"); setModal(null); resetFund(); load(); } catch (error) { showToast(error instanceof Error ? error.message : "Unable to save fund", "error"); } finally { setSaving(false); } };
  const submitTransaction = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const payload = { type: transactionType, transacted_at: transactedAt, amount: Number(amount), description, notes: transactionNotes }; if (editingTransaction) await api.patch(`/fund-transactions/${editingTransaction.id}`, payload); else await api.post(`/funds/${transactionFund}/transactions`, payload); showToast(editingTransaction ? "Transaction updated." : "Transaction created.", "success"); setModal(null); resetTransaction(); load(); } catch (error) { showToast(error instanceof Error ? error.message : "Unable to save transaction", "error"); } finally { setSaving(false); } };
  const deleteItem = async (url: string, message: string, close?: () => void) => { if (!window.confirm(message)) return; try { await api.delete(url); close?.(); load(); showToast("Deleted successfully.", "success"); } catch (error) { showToast(error instanceof Error ? error.message : "Unable to delete item", "error"); } };
  const cards = useMemo(() => data ? [["Total Balance", data.total_balance], ["Total Inflows", data.total_inflows], ["Total Outflows", data.total_outflows]] : [], [data]);
  return <AdminShell title="Funds"><div className="mt-8 space-y-6">
    <div className="flex flex-col justify-between gap-3 sm:flex-row"><p className="text-sm text-[#777]">Manage fund accounts, deposits, withdrawals, and running balances.</p><div className="flex flex-wrap gap-3"><button className="border border-black/10 px-4 py-3 text-sm" onClick={() => { resetFund(); setModal("fund"); }}>+ Add fund</button><button className="bg-[#ff641f] px-4 py-3 text-sm font-bold text-white" onClick={() => { resetTransaction(); setModal("transaction"); }}>+ Add transaction</button></div></div>
    <div className="grid gap-4 sm:grid-cols-3">{cards.map(([label, value]) => <section className="rounded border border-black/10 bg-white p-5" key={label as string}><p className="text-xs text-[#777]">{label}</p><strong className="mt-3 block text-2xl text-[#ff641f]">{money.format(value as number)}</strong></section>)}</div>
    <section className="rounded border border-black/10 bg-white p-5"><h2 className="font-semibold">Fund accounts</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data?.funds.map(fund => <article className="rounded border border-black/10 p-4" key={fund.id}><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{fund.name}</h3><p className="text-xs capitalize text-[#888]">{fund.type}</p>{fund.account_name && <p className="mt-2 text-xs text-[#777]">{fund.account_name}</p>}{fund.account_number && <p className="text-xs text-[#777]">{fund.account_number}</p>}</div><strong className="text-right text-[#ff641f]">{money.format(fund.balance)}</strong></div>{fund.qr_code_url && <div className="mt-3 flex items-end gap-3"><img className="h-20 w-20 rounded border border-black/10 object-contain" src={fund.qr_code_url} alt={`${fund.name} QR code`} /><a className="text-xs text-[#ff641f]" href={fund.qr_code_url} download={`${fund.name}-qr-code`}>Download QR</a></div>}    <div className="mt-4 flex justify-end text-sm"><RowActions actions={[{ label: "Edit", onClick: () => { setEditingFund(fund); setName(fund.name); setFundType(fund.type); setOpening(fund.opening_balance); setFundNotes(fund.notes ?? ""); setAccountName(fund.account_name ?? ""); setAccountNumber(fund.account_number ?? ""); setQrCode(null); setModal("fund"); } }, { label: "Delete", danger: true, onClick: () => void deleteItem(`/funds/${fund.id}`, "Delete this fund and all its transactions?") }]} /></div></article>)}</div></section>
    <div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_200px_180px_180px]"><input className="border border-black/10 bg-white px-3 py-2.5 text-sm" placeholder="Search fund, description, or notes..." value={search} onChange={event => setSearch(event.target.value)} /><select className="border border-black/10 bg-white px-3 py-2.5 text-sm" value={fundId} onChange={event => setFundId(event.target.value)}><option value="">All funds</option>{data?.funds.map(fund => <option value={fund.id} key={fund.id}>{fund.name}</option>)}</select><select className="border border-black/10 bg-white px-3 py-2.5 text-sm" value={type} onChange={event => setType(event.target.value)}><option value="">All transaction types</option><option value="inflow">Inflows</option><option value="outflow">Outflows</option></select><select className="border border-black/10 bg-white px-3 py-2.5 text-sm" value={sort} onChange={event => setSort(event.target.value)}><option value="date_latest">Date: Latest</option><option value="date_oldest">Date: Oldest</option><option value="amount_asc">Amount: Ascending</option><option value="amount_desc">Amount: Descending</option><option value="type_inflow">Type: Inflows</option><option value="type_outflow">Type: Outflows</option></select></div>
    <div className="overflow-x-auto rounded border border-black/10 bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-black/10 text-[10px] uppercase tracking-widest text-[#888]"><tr><th className="p-4">Date</th><th className="p-4">Fund</th><th className="p-4">Type</th><th className="p-4">Description</th><th className="p-4 text-right">Amount</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{data?.transactions.length ? data.transactions.map(transaction => <tr className="border-b border-black/[.06]" key={transaction.id}><td className="whitespace-nowrap p-4 text-[#777]">{dateLabel(transaction.transacted_at)}</td><td className="p-4">{transaction.fund?.name}</td><td className={`p-4 font-semibold ${transaction.type === "inflow" ? "text-emerald-600" : "text-red-600"}`}>{transaction.type}</td><td className="p-4 text-[#777]">{transaction.description}</td><td className="p-4 text-right font-semibold">{money.format(Number(transaction.amount))}</td>    <td className="whitespace-nowrap p-4 text-right"><RowActions actions={[{ label: "View", onClick: () => setSelectedTransaction(transaction) }, { label: "Edit", onClick: () => { setEditingTransaction(transaction); setTransactionType(transaction.type); setTransactionFund(String(transaction.fund_id)); setTransactedAt(transaction.transacted_at.slice(0, 16)); setAmount(transaction.amount); setDescription(transaction.description); setTransactionNotes(transaction.notes ?? ""); setModal("transaction"); } }, { label: "Delete", danger: true, onClick: () => void deleteItem(`/fund-transactions/${transaction.id}`, "Delete this transaction?") }]} /></td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-[#777]">No transactions found.</td></tr>}</tbody></table></div>
    {selectedTransaction && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section className="w-full max-w-lg bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-[#ff641f]">Transaction details</p><h2 className="mt-2 text-2xl font-semibold">{selectedTransaction.description}</h2></div><button className="text-2xl text-[#777]" onClick={() => setSelectedTransaction(null)}>×</button></div><dl className="mt-6 space-y-3 text-sm"><div><dt className="text-xs uppercase text-[#888]">Fund</dt><dd>{selectedTransaction.fund?.name}</dd></div><div><dt className="text-xs uppercase text-[#888]">Date</dt><dd>{dateLabel(selectedTransaction.transacted_at)}</dd></div><div><dt className="text-xs uppercase text-[#888]">Type</dt><dd className="capitalize">{selectedTransaction.type}</dd></div><div><dt className="text-xs uppercase text-[#888]">Amount</dt><dd className="text-xl font-bold text-[#ff641f]">{money.format(Number(selectedTransaction.amount))}</dd></div><div><dt className="text-xs uppercase text-[#888]">Notes</dt><dd className="whitespace-pre-wrap text-[#555]">{selectedTransaction.notes || "—"}</dd></div></dl><div className="mt-6 flex justify-end gap-3"><button className="text-red-600" onClick={() => void deleteItem(`/fund-transactions/${selectedTransaction.id}`, "Delete this transaction?", () => setSelectedTransaction(null))}>Delete</button><button className="bg-[#151515] px-4 py-2 text-sm font-bold text-white" onClick={() => { setEditingTransaction(selectedTransaction); setTransactionType(selectedTransaction.type); setTransactionFund(String(selectedTransaction.fund_id)); setTransactedAt(selectedTransaction.transacted_at.slice(0, 16)); setAmount(selectedTransaction.amount); setDescription(selectedTransaction.description); setTransactionNotes(selectedTransaction.notes ?? ""); setSelectedTransaction(null); setModal("transaction"); }}>Edit</button></div></section></div>}
    {modal === "fund" && <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/50 p-4"><form className="w-full max-w-lg bg-white p-6" onSubmit={submitFund}><h2 className="text-2xl font-semibold">{editingFund ? "Edit fund" : "Add fund"}</h2><div className="mt-5 space-y-4"><label className="block text-xs text-[#777]">Fund name<input required className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={name} onChange={event => setName(event.target.value)} /></label><label className="block text-xs text-[#777]">Fund type<select className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={fundType} onChange={event => setFundType(event.target.value)}><option value="cash">Cash</option><option value="bank">Bank</option><option value="e-wallet">E-wallet</option><option value="other">Other</option></select></label><label className="block text-xs text-[#777]">Account name (optional)<input className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" placeholder="Full name of the account holder" value={accountName} onChange={event => setAccountName(event.target.value)} /></label><label className="block text-xs text-[#777]">Account number (optional)<input className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={accountNumber} onChange={event => setAccountNumber(event.target.value)} /></label><label className="block text-xs text-[#777]">QR code image (optional)<input className="mt-2 w-full border border-dashed border-black/20 px-3 py-3 text-sm" type="file" accept="image/*" onChange={event => setQrCode(event.target.files?.[0] ?? null)} />{editingFund?.qr_code_url && !qrCode && <img className="mt-3 h-24 w-24 rounded border border-black/10 object-contain" src={editingFund.qr_code_url} alt="Current QR code" />}{qrCode && <p className="mt-2 text-xs text-[#777]">{qrCode.name}</p>}</label><label className="block text-xs text-[#777]">Opening balance<input required min="0" step="0.01" type="number" className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={opening} onChange={event => setOpening(event.target.value)} /></label><label className="block text-xs text-[#777]">Notes<textarea className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={fundNotes} onChange={event => setFundNotes(event.target.value)} /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" className="border px-4 py-2 text-sm" onClick={() => setModal(null)}>Cancel</button><button disabled={saving} className="bg-[#151515] px-4 py-2 text-sm font-bold text-white">{saving ? "Saving..." : "Save fund"}</button></div></form></div>}
    {modal === "transaction" && <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/50 p-4"><form className="w-full max-w-lg bg-white p-6" onSubmit={submitTransaction}><h2 className="text-2xl font-semibold">{editingTransaction ? "Edit transaction" : "Add transaction"}</h2><div className="mt-5 space-y-4"><label className="block text-xs text-[#777]">Fund<select required className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={transactionFund} onChange={event => setTransactionFund(event.target.value)}><option value="">Select fund</option>{data?.funds.map(fund => <option value={fund.id} key={fund.id}>{fund.name}</option>)}</select></label><fieldset><legend className="text-xs text-[#777]">Transaction type</legend><div className="mt-2 flex gap-5 text-sm"><label><input type="radio" checked={transactionType === "inflow"} onChange={() => setTransactionType("inflow")} /> Inflow</label><label><input type="radio" checked={transactionType === "outflow"} onChange={() => setTransactionType("outflow")} /> Outflow</label></div></fieldset><label className="block text-xs text-[#777]">Date and time    <DateTimePicker required mode="datetime" value={transactedAt} onChange={setTransactedAt} className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" /></label><label className="block text-xs text-[#777]">Description<input required className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={description} onChange={event => setDescription(event.target.value)} /></label><label className="block text-xs text-[#777]">Amount<input required min="0.01" step="0.01" type="number" className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={amount} onChange={event => setAmount(event.target.value)} /></label><label className="block text-xs text-[#777]">Notes<textarea className="mt-2 w-full border border-black/10 px-3 py-2.5 text-sm" value={transactionNotes} onChange={event => setTransactionNotes(event.target.value)} /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" className="border px-4 py-2 text-sm" onClick={() => setModal(null)}>Cancel</button><button disabled={saving} className="bg-[#151515] px-4 py-2 text-sm font-bold text-white">{saving ? "Saving..." : "Save transaction"}</button></div></form></div>}
  </div></AdminShell>;
}
