import { useEffect, useMemo, useState } from "react";
import { AdminShell } from "../components/AdminShell";
import { DateTimePicker } from "../components/DateTimePicker";
import { useToast } from "../components/Ui";
import api from "../lib/api";
import type { FundRecord, FundTransactionRecord } from "../types";

type ReportData = { funds: Pick<FundRecord, "id" | "name">[]; transactions: (FundTransactionRecord & { payment?: { booking?: { reference?: string; customer?: { name: string }; vehicle?: { name?: string; brand: string; model: string } } }; expense?: { category?: string; expense_type?: string; vehicle?: { name?: string; brand: string; model: string } } })[]; total_income: number; total_expenses: number; net_income: number; transaction_count: number };
const money = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" });
const dateLabel = (value: string) => new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });

export default function IncomeFlowReportPage() {
  const { showToast } = useToast();
  const [data, setData] = useState<ReportData | null>(null);
  const [search, setSearch] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [fundId, setFundId] = useState(""); const [direction, setDirection] = useState(""); const [source, setSource] = useState(""); const [category, setCategory] = useState(""); const [sort, setSort] = useState("date_latest");
  const query = useMemo(() => { const params = new URLSearchParams({ sort }); if (search.trim()) params.set("search", search.trim()); if (from) params.set("from", from); if (to) params.set("to", to); if (fundId) params.set("fund_id", fundId); if (direction) params.set("direction", direction); if (source) params.set("source", source); if (category) params.set("category", category); return params; }, [search, from, to, fundId, direction, source, category, sort]);
  const load = () => api.get<ReportData>(`/reports/income-flow?${query}`).then(result => setData(result.data)).catch(error => showToast(error instanceof Error ? error.message : "Unable to load income flow report", "error"));
  useEffect(() => { const timer = window.setTimeout(load, 250); return () => window.clearTimeout(timer); }, [query.toString()]);
  const downloadCsv = async () => { try { const response = await api.get(`/reports/income-flow?${query}&csv=1`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = "income-flow.csv"; link.click(); URL.revokeObjectURL(url); } catch (error) { showToast(error instanceof Error ? error.message : "Unable to export report", "error"); } };
  return <AdminShell title="Income Flow Report" reportsOnly><div className="mt-8 space-y-6">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><p className="text-sm text-[#777]">Review money coming into and leaving your operation.</p><button className="bg-[#151515] px-4 py-3 text-sm font-bold text-white" onClick={() => void downloadCsv()}>Export CSV</button></div>
    <div className="grid gap-4 sm:grid-cols-3">{[["Total income", data?.total_income ?? 0], ["Total expenses", data?.total_expenses ?? 0], ["Net income", data?.net_income ?? 0]].map(([label, value]) => <section className="rounded border border-black/10 bg-white p-5" key={label as string}><p className="text-xs text-[#777]">{label}</p><strong className={`mt-3 block text-2xl ${(value as number) < 0 ? "text-red-600" : "text-[#ff641f]"}`}>{money.format(value as number)}</strong></section>)}</div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="border border-black/10 bg-white px-3 py-2.5 text-sm" placeholder="Search description, fund, booking, vehicle..." value={search} onChange={event => setSearch(event.target.value)} /><DateTimePicker value={from} onChange={setFrom} className="border border-black/10 bg-white px-3 py-2.5 text-sm" placeholder="From date" /><DateTimePicker value={to} onChange={setTo} className="border border-black/10 bg-white px-3 py-2.5 text-sm" placeholder="To date" /><select className="border border-black/10 bg-white px-3 py-2.5 text-sm" value={sort} onChange={event => setSort(event.target.value)}><option value="date_latest">Date: Latest</option><option value="date_oldest">Date: Oldest</option><option value="amount_asc">Amount: Ascending</option><option value="amount_desc">Amount: Descending</option><option value="type_inflow">Type: Inflows</option><option value="type_outflow">Type: Outflows</option></select><select className="border border-black/10 bg-white px-3 py-2.5 text-sm" value={fundId} onChange={event => setFundId(event.target.value)}><option value="">All funds</option>{data?.funds.map(fund => <option value={fund.id} key={fund.id}>{fund.name}</option>)}</select><select className="border border-black/10 bg-white px-3 py-2.5 text-sm" value={direction} onChange={event => setDirection(event.target.value)}><option value="">All directions</option><option value="inflow">Income</option><option value="outflow">Outflow</option></select><select className="border border-black/10 bg-white px-3 py-2.5 text-sm" value={source} onChange={event => setSource(event.target.value)}><option value="">All sources</option><option value="booking_payment">Booking payment</option><option value="expense">Expense</option><option value="manual">Manual fund transaction</option></select><select className="border border-black/10 bg-white px-3 py-2.5 text-sm" value={category} onChange={event => setCategory(event.target.value)}><option value="">All expense categories</option><option value="unit-related">Unit-Related</option><option value="general">General Expense</option></select></div>
    <div className="overflow-x-auto rounded border border-black/10 bg-white"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b border-black/10 text-[10px] uppercase tracking-widest text-[#888]"><tr><th className="p-4">Date</th><th className="p-4">Fund</th><th className="p-4">Source</th><th className="p-4">Reference / Context</th><th className="p-4">Description</th><th className="p-4 text-right">Amount</th></tr></thead><tbody>{data?.transactions.length ? data.transactions.map(transaction => { const sourceLabel = transaction.payment ? "Booking payment" : transaction.expense ? "Expense" : "Manual"; const context = transaction.payment?.booking?.vehicle?.name || transaction.payment?.booking?.customer?.name || transaction.expense?.vehicle?.name || transaction.expense?.expense_type || "—"; return <tr className="border-b border-black/[.06]" key={transaction.id}><td className="whitespace-nowrap p-4 text-[#777]">{dateLabel(transaction.transacted_at)}</td><td className="p-4">{transaction.fund?.name ?? "—"}</td><td className="p-4">{sourceLabel}</td><td className="p-4">{transaction.payment?.booking?.reference ?? context}</td><td className="p-4 text-[#777]">{transaction.description}</td><td className={`p-4 text-right font-semibold ${transaction.type === "inflow" ? "text-emerald-600" : "text-red-600"}`}>{transaction.type === "inflow" ? "+" : "−"}{money.format(Number(transaction.amount))}</td></tr>; }) : <tr><td className="p-8 text-center text-[#777]" colSpan={6}>No transactions found for the selected filters.</td></tr>}</tbody></table></div>
  </div></AdminShell>;
}
