import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { AdminShell } from '../components/AdminShell'
import api from '../lib/api'
import type { Paginated, VehicleRecord } from '../types'

export default function VehiclesPage() {
  const [vehicles, setVehicles] = useState<VehicleRecord[]>([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ brand: '', model: '', type: 'car', plate_number: '', daily_rate: '' })
  const loadVehicles = useCallback(() => { setLoading(true); api.get<Paginated<VehicleRecord>>(`/vehicles?per_page=50&search=${encodeURIComponent(search)}${status ? `&status=${status}` : ''}`).then(result => setVehicles(result.data.data)).catch(e => setError(e instanceof Error ? e.message : 'Unable to load vehicles')).finally(() => setLoading(false)) }, [search, status])
  useEffect(() => { const timer = window.setTimeout(loadVehicles, 0); return () => window.clearTimeout(timer) }, [loadVehicles])
  const createVehicle = async (event: FormEvent) => { event.preventDefault(); try { await api.post('/vehicles', { ...form, daily_rate: Number(form.daily_rate) }); setForm({ brand: '', model: '', type: 'car', plate_number: '', daily_rate: '' }); setShowForm(false); loadVehicles() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create vehicle') } }
  return <AdminShell title="Vehicle management"><div className="mt-8 border border-black/10 bg-white p-4 md:p-6"><div className="flex flex-col gap-3 md:flex-row"><input className="flex-1 border border-black/10 bg-[#f8f7f5] px-4 py-3 text-sm outline-none focus:border-[#ff641f]" placeholder="Search brand, model, or plate..." value={search} onChange={e => setSearch(e.target.value)} /><select className="border border-black/10 bg-[#f8f7f5] px-4 py-3 text-sm" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="available">Available</option><option value="maintenance">Maintenance</option><option value="archived">Archived</option></select><button className="bg-[#ff641f] px-5 py-3 text-sm font-bold text-white" onClick={() => setShowForm(!showForm)}>+ Add vehicle</button></div>{showForm && <form className="mt-5 grid gap-3 border-t border-black/10 pt-5 md:grid-cols-5" onSubmit={createVehicle}>{[['brand', 'Brand'], ['model', 'Model'], ['plate_number', 'Plate number'], ['daily_rate', 'Daily rate']].map(([key, label]) => <input key={key} className="border border-black/10 px-3 py-2 text-sm" placeholder={label} value={form[key as keyof typeof form]} onChange={e => setForm({ ...form, [key]: e.target.value })} required />)}<select className="border border-black/10 px-3 py-2 text-sm" value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="car">Car</option><option value="motorcycle">Motorcycle</option></select><button className="bg-[#151515] px-4 py-2 text-sm font-bold text-white md:col-span-5">Save vehicle</button></form>}{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-black/10 text-[10px] uppercase tracking-widest text-[#888]"><tr><th className="pb-3">Vehicle</th><th className="pb-3">Type</th><th className="pb-3">Plate</th><th className="pb-3">Rate</th><th className="pb-3">Status</th></tr></thead><tbody>{loading ? <tr><td className="py-8 text-[#888]" colSpan={5}>Loading vehicles...</td></tr> : vehicles.map(vehicle => <tr className="border-b border-black/[.06]" key={vehicle.id}><td className="py-4 font-semibold">{vehicle.brand} {vehicle.model}</td><td className="py-4 capitalize text-[#777]">{vehicle.type}</td><td className="py-4 text-[#777]">{vehicle.plate_number}</td><td className="py-4">₱{Number(vehicle.daily_rate).toLocaleString()}/day</td><td className="py-4">{vehicle.status}</td></tr>)}</tbody></table></div></div></AdminShell>
}
